global:
  application_name: SYNCES
  branch: null
  default_ec2_keyname: null
  default_platform: node.js
  default_region: eu-west-3
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
